# Generated by Django 3.0.5 on 2020-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, upload_to='static/product-image/')),
                ('product_size', models.CharField(choices=[('A2', 'A2 Paper'), ('A3', 'A3 Paper'), ('A4', 'A4 Paper'), ('A5', 'A5 Paper')], max_length=3, verbose_name='type')),
            ],
        ),
    ]
